### ISSUE TITLE
Bad home directory on kernel.source

### ISSUE THREAD

**Issue by StefanoMarina** [dddomin3/DSPi#48]
_make bcm2709_defconfig_ fails because 

`scripts/Kconfig.include:39: compiler '/home/cheekymusic/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc' not found
`
kernel.source shows all path with home directory as /home/cheekymusic. Replacing all references  with "$HOME",  fixed the issue. I don't have linux and tool folders on home dir but made a symlink and seems to be working fine.

**Comment by StefanoMarina** [comment]
Just figured out that this issue is explained later. I think action list should be revised but it's more like an enhanchment than a issue per-se

**Comment by dddomin3** [comment]
Either way! My apologies, a lot of this is outdated unfortunately, since
it's on such an old version of the OS, but I haven't updated this since
I've had no issues, especially since adopting the pisound card, and i don't
feel the need to break my music set up every time I want to update this
(yeah, I could buy another pi to experiment on, but I honestly don't have
the time to devote to that).

If you'd like to update the repo to your needs, please feel free to fork
and PR it back in, or I do not mind adding you as a collaborator.

Sadly, I think this is one of the newer sources of compiling a
preemptible kernel for the raspi, but it's more out of date than I believe
anyone would like. Please feel free to tear it apart as viciously as you
like: I only take pride in helping others and being a resource to the
community, not for my specific methods or code.
